find_package(LibElf REQUIRED)
find_package(LibZ REQUIRED)
find_package(LibBpf REQUIRED)
find_package(LibPcap REQUIRED)
find_package(Spdlog REQUIRED)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED)
add_compile_options(-Wall -Werror -g -O3)
add_subdirectory(app)
add_subdirectory(bpf)
add_subdirectory(output)
add_subdirectory(symdb)
add_subdirectory(trace)
add_subdirectory(utils)